ParkingReg.Web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using ParkingReg.Models;
using ParkingReg.Utils;
using ParkingReg.Web.Models;
using ParkingReg.Web.Utils;
using System.Diagnostics;

namespace ParkingReg.Web.Controllers;

public class AdminController : Controller
{

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
    [HttpGet]
    public IActionResult EmailManager() { return View(); }

    [HttpGet]
    public IActionResult Parkings() { return View(); }
    [HttpGet]
    public IActionResult ParkingCheck() { return View("ParkingLookup"); }

    [HttpGet]
    public IActionResult GetParkings() { return View(); }
    [HttpGet]
    public IActionResult GetActiveParkings()
    {
        List<ParkingExtended> Parkings = new List<ParkingExtended>();
        SequelAdmin seq = new SequelAdmin();
        try
        {
            Parkings = seq.GetActiveParkings();
            return Json(new GeneralResponse(true, "good", Parkings));
        }
        catch (Exception e)
        {
            return Json(new GeneralResponse(false, e.Message));
        }

    }
    [HttpGet]
    public IActionResult ParkingLookup(string regnr)
    {
        SequelAdmin seq = new SequelAdmin();
        try
        {
            ParkingExtended Parking = seq.LookUpParking(regnr);
            if (Parking == null)
            {
                return Json(new GeneralResponse(false, "No valid parking"));
            }
            return Json(new GeneralResponse(true, "good", Parking));
        }
        catch (Exception e)
        {
            return Json(new GeneralResponse(false, e.Message));
        }

    }

    [HttpPost]
    public IActionResult AddEmail([FromBody] WhiteListEmailModel WLEM) 
    {
        SequelAdmin seq = new SequelAdmin();
        try
        {
            seq.AddWhiteListedMail(WLEM);
            return Json(new GeneralResponse(true, "Email added"));
        }
        catch (Exception ex)
        {
            return Json(new GeneralResponse(false, ex.Message));
        }
    }


    
}

ParkingReg.Web/Controllers/DummyController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingReg.Models;
using ParkingReg.Web.Models;
using ParkingReg.Web.Utils;
using System.Diagnostics;

namespace ParkingReg.Web.Controllers;

public class DummyController : Controller
{


    public IActionResult Index()
    {
        return View();
    }
    public IActionResult GetEmails()
    {
        try
        {
            List<EmailModel> emails = EmailHandler.GetEmails();

            return Json(new GeneralResponse(true, "emails", emails));
        } catch (Exception E)
        {
            return Json(new GeneralResponse(false, "emails", E.Message));
        }
        
    }


    
}

ParkingReg.Web/Controllers/ParkingController.cs
using System.Diagnostics;
using ParkingReg.Utils;
using Microsoft.AspNetCore.Mvc;
using ParkingReg.Web.Models;
using ParkingReg.Models;
using ParkingReg.Web.Utils;

namespace ParkingReg.Web.Controllers;

public class ParkingController : Controller
{
    [HttpPost]
    public IActionResult HandleEmail([FromForm] HandleEmailModel HEM)
    {
        string email = HEM.Email;
        SequelWhitelistEmail seq = new SequelWhitelistEmail();
        if(seq.CheckWhitelistEmail(email))
        {
            int emailId = seq.GetWhitelistEmailId(email);
            SequelVtk seqvtk = new SequelVtk();
            var request = HttpContext.Request;
            string baseUrl = $"{request.Scheme}://{request.Host}";
            seqvtk.GenerateVtk(emailId, baseUrl);
            return View("EmailSent", HEM);
        }
        return Json(new GeneralResponse(false, "Failed, invalid email"));
    }
    public IActionResult HandlePark([FromForm] ParkReq PR)
    {
        if (!DateTimeHelper.ValidateTime(PR.Duration))
            return View("ParkingRejected");

        SequelParkReg seq = new SequelParkReg();
        if (!seq.HasValidParking(PR.Regnr))
        {
            SequelVtk seqvtk = new SequelVtk();
            Vtk vtk = seqvtk.GetVtkByToken(PR.Token);

            PR.EmailId = vtk.EmailId;
            SequelWhitelistEmail seqWLE = new SequelWhitelistEmail();
            string email = seqWLE.GetWhitelistEmail(PR.EmailId);
            try
            {
                seq.SubmitParking(PR);
            } catch
            {
                return View("ParkingRejected");
            }
            
            Parking prk = seq.GetParking(PR.Regnr);
            EmailHandler.SendEmail(email, "Park registered", $"Yo parking fo car {PR.Regnr} was registered");
            seqvtk.InvalidateVtks(PR.EmailId);
            return View("ParkingRegistered", prk);
        }
        else
        {
            return Json(new GeneralResponse(false, "Parking already exists for this vehicle"));
        }
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string t = null, string regnr = null)
    {
        if (!string.IsNullOrEmpty(regnr) && !string.IsNullOrEmpty(t))
        {
            SequelVtk seqvtk = new SequelVtk();
            Vtk vtk = seqvtk.GetVtkByToken(t);
            if (vtk == null)
            {
                return Json(new GeneralResponse(false, "Invalid token"));
            }
            SequelParkReg seq = new SequelParkReg();
            if (!seq.HasValidParking(regnr))
            {
                FetchCarInfo fetchCarInfo = new FetchCarInfo();
                try
                {
                    vtk.CarInfo = await fetchCarInfo.GetCarInfoAsync(regnr);
                } catch
                {
                    vtk.CarInfo = "Ukjent bil";
                }
                
                vtk.Regnr = regnr;
                return View("ChoosePark",vtk);
            } else
            {
                Parking park = seq.GetParking(regnr);
                return View("AlreadyParked", park);
            }


        } else if (!string.IsNullOrEmpty(t))
        {
            SequelVtk seqvtk = new SequelVtk();
            Vtk vtk = seqvtk.GetVtkByToken(t);
            if (vtk == null)
            {
                return View();
            }
            else
            {
                return View("EnterReg", vtk);
            }
        } else
        {
            return View();
        }
            

    }
}

ParkingReg.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParkingReg.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ParkingReg.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParkingReg.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parking" asp-action="Index">Register parking</a>
                        </li>
                        <li class="nav-item"><a class="nav-link text-dark"> | User - Admin | </a></li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dummy" asp-action="Index">Dummy Inbox</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="EmailManager">Add Emails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Parkings">Parkings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ParkingCheck">Parking lookup</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ParkingReg.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>